### ISSUE TITLE
Cannot pan map in QML

### ISSUE THREAD

**Issue by phamanhtuan** [shentok/marble#1]
Hi,
I create an app using QML to show marble. But I cannot pan the map.
It warned "QGraphicsItem::ungrabMouse: not a mouse grabber"

Can anyone give me some idea?

Thanks,

**Comment by phamanhtuan** [comment]
I found that the proxy wrapping marble widget handles all event propagate in QML but it does not forward to the widget.
I try to write my own proxy inherit QGraphicsProxyWidget to forward events to marble widget but that widget does not provide any api for me to do that.
Any help would be appriciated!

Thanks

**Comment by shentok** [comment]
Hi,

would you mind getting in contact with the Marble developers via one of the ways listed in [1]? This way, you can reach the whole Marble team instead of just me.

Thanks!

[1] https://marble.kde.org/support.php
